#!/bin/bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "${parent_path}"

function configure
{
  [ ! -d ".build" ] && command mkdir $1 && cd $1 && cmake ..
  [ -d ".build" ] && cd $1 && cmake ..
}

configure .build
make && make install
cd ..
strip -S --strip-unneeded --remove-section=.comment --remove-section=.note --remove-section=.note.gnu.build-id --remove-section=.note.ABI-tag output/Client
strip -S --strip-unneeded --remove-section=.comment --remove-section=.note --remove-section=.note.gnu.build-id --remove-section=.note.ABI-tag output/Server
